### ISSUE TITLE
Unzip doesn't handle embedded folder in zip file

### ISSUE THREAD

**Issue by riwide** [agn453/UNZIP-CPM-Z80#2]
[Hisoft Modula 2.zip](https://github.com/agn453/UNZIP-CPM-Z80/files/8125594/Hisoft.Modula.2.zip)

Unzipping this seems to make the embedded folder name as the file name after unzip (truncated), but the file type is the type as expected.
I would expect the embedded folder name to be sort of ignored.

**Comment by agn453** [comment]
Which flavour and version of UNZIP are you using?

Lars Nelson did some work stripping pathnames for the Z-System release - and this hasn't been
backported to the other versions (I think).  I'll have a look at this when I get time this coming weekend.

In the meantime as a work-around, please try re-creating the zip file without pathnames (extract the files then create a new zip by adding files without a directory specification - i.e. do it when the current directory has the files you wish to add).

If you're using Windows, select the group of files (using Ctrl-left mouse click to select each file) right click and choose Send-to compressed folder from the File Explorer.

For Linux/macOS something like -

```
cd /tmp
unzip ~/Downloads/Hisoft.Modula.2.zip
cd Hisoft\ Modula\2/
zip -j hisoftmod2.zip ./*
```
